name: perses
channels:
    - omnia
    - omnia/label/dev
    - omnia/label/beta
    - openeye
dependencies:
    - python
    - setuptools
    - numpy
    - scipy
    - numexpr
    - autograd
    - pymbar
    - cuda92
    - openmm ==7.3.0
    - parmed
    - openmoltools
    - alchemy >=1.2.3
    - openmmtools
    - numba
    - netcdf4
    - matplotlib
    - seaborn
    - pdbfixer
    - mdtraj
    - parmed # for testing/debugging
    - pdbfixer
    - lxml
    - networkx >=2.0
    - yank
    - numpydoc
    - openeye-toolkits
